name: Linting

on:
  push:
    branches:
      - "*"
    paths:
      - "**.js*"
      - "**.ts*"
      - "package*.json"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.js*"
      - "**.ts*"
      - "package*.json"
      - ".github/workflows/lint.yml"

env:
  NODE_ENV: development

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: yarn

      - run: yarn lint
